# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3bd60c1ddbca52405fbe4423b70223c7d1176f90a74aa5320f97c6b0ee4b3a4a990cf8d51644581ce935db3ada1d476cac6d2adde8869f54dff46e155200913

test:
  secret_key_base: 537441890aaf268d9e73424881774834b9595dcf075fe61d43f7d86822ea11a71870cf7fa2436b8192481c4cb6c9a1786aee2764a436548cbd09e78837388885

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
